python run.py \
  --is_training 1 \
  --model_id Weather_96_96_exp1_HScales \
  --model HyperbolicForecasting \
  --data custom_decomposition \
  --root_path ./time-series-dataset/dataset/ \
  --data_path weather.csv \
  --features M \
  --num_basis 10 \
  --seq_len 96 \
  --pred_len 96 \
  --lradj "constant" \
  --embed_dim 32 \
  --hidden_dim 64 \
  --batch_size 32 \
  --learning_rate 0.0001 \
  --train_epochs 30 \
  --use_decomposition \
  --enc_in 21 \
  --use_tensorboard \
  --patience 6 \
  --manifold_type "Euclidean" \
  --use_hierarchy \
  --use_attention_pooling 

