# Weather dataset - Trend in Hyperbolic Space
python run.py \
  --is_training 1 \
  --root_path ./time-series-dataset/dataset/ \
  --data_path weather.csv \
  --model_id Weather_trend_hyperbolic \
  --model HyperbolicForecasting \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 0 \
  --pred_len 96 \
  --enc_in 21 \
  --encode_dim 32 \
  --hidden_dim 64 \
  --num_basis 10 \
  --batch_size 128 \
  --learning_rate 0.001 \
  --train_epochs 20 \
  --patience 5 \
  --manifold_type "Lorentzian" \
  --curvature 1.0 \
  --use_learnable_decomposition \
  --use_wandb

python run.py \
  --is_training 1 \
  --root_path ./time-series-dataset/dataset/ \
  --data_path weather.csv \
  --model_id Weather_trend_hyperbolic \
  --model HyperbolicForecasting \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 0 \
  --pred_len 192 \
  --enc_in 21 \
  --encode_dim 32 \
  --hidden_dim 64 \
  --num_basis 10 \
  --batch_size 128 \
  --learning_rate 0.001 \
  --train_epochs 20 \
  --patience 5 \
  --manifold_type "Lorentzian" \
  --curvature 1.0 \
  --use_learnable_decomposition \
  --use_wandb 

python run.py \
  --is_training 1 \
  --root_path ./time-series-dataset/dataset/ \
  --data_path weather.csv \
  --model_id Weather_trend_hyperbolic \
  --model HyperbolicForecasting \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 0 \
  --pred_len 336 \
  --enc_in 21 \
  --encode_dim 32 \
  --hidden_dim 64 \
  --num_basis 10 \
  --batch_size 128 \
  --learning_rate 0.001 \
  --train_epochs 20 \
  --patience 5 \
  --manifold_type "Lorentzian" \
  --curvature 1.0 \
  --use_learnable_decomposition \
  --use_wandb \
  --use_revin \
  --use_segments 

